# file roles/swarm-leader/tasks/main.yml

- name: initialize swarm cluster
  shell: docker node ls || docker swarm init

- name: register manager join token
  shell: docker swarm join-token --quiet manager
  register: swarm_token_manager

- name: register worker join token
  shell: docker swarm join-token --quiet worker
  register: swarm_token_worker

# - debug: var=swarm_token_manager
# - debug: var=hostvars[inventory_hostname]