# file roles/docker-engine/tasks/main.yml

- name: remove docker
  apt:
    name: docker
    state: absent

- name: remove docker-engine
  apt:
    name: docker-engine
    state: absent

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: install ca-certificates
  apt:
    name: ca-certificates
    state: latest

- name: install curl
  apt:
    name: curl
    state: latest

- name: install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: install official key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: setup the stable repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker-ce
  apt:
    update_cache: yes
    name: docker-ce=17.03.0~ce-0~ubuntu-xenial
    state: present

- name: enable docker service
  systemd:
    name: docker
    enabled: yes

- name: add to docker group
  user:
    name: ubuntu
    append: true
    groups: docker